sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ScUCMxw3QB8YLhFNoHyxCaA6t4ZFRk4cJKNKMpyqcuGQ9hvEaa1s0R3WVtrooDNkCJE7ClWDFaVdAX1Gz1XXTuEh1LITLB37T8dIrr20Z84hsugdFiaSWQJmKMN75GNIKHgQzgeIvUOj89pOogeauKajxdHh3yT6B7dsp91KfiXvWo5pSzgwHXunX/bfWEr2ZNpPB4XaOGRD92MVNp3MlZ+IGm3qj4HZ93WvdTM4yFXuQzqx9b/BU4pkW6kNer6tW8z0xE7XGJ4KU3LR+3QcnD5Dyaz25YbBCg00iXL7ByAPwNoEDkIh9LTbx5NyTFi6i2UMJiItWkwJKKwVZPZRgFeGZr/HOQB+DC4Vf0N80jo2BepBUyUc6AR4a1VEUIIl7b8ptzB7O0ufjroi2MDT047HVDHIyDDPewLCCJQCDGO1NEjtHDNWa3caCCjKWxng0qv02fQ/5wJsdwmRTe8B+3dWohXAwgALMnnyl/XId8Cl/9/275yJaME35IrcuGjUtiQyUwEagrVlEfZ4rLVDTfZ5qdMBbTd6H+nbCGiya/FcYWDBTY9jFXm2/nJtXEM9aEZKGDOcBRBcbpFSgTxD5EmzirHcb1lyPHSPjXi/tH/LTPd7RtU4hpkS4WULifUKpMli4xK8yxNWQ0WKvE94MNKNvO2a4dtH3T3lmZK6Mgk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Return-of-Tarzan_81
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy